// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLuuMiz3vB55bILYw5wslaXmMDxQ9-IU',
    appId: '1:34126164944:web:55c6ce7e05819cc88abfd5',
    messagingSenderId: '34126164944',
    projectId: 'authfancy',
    authDomain: 'authfancy.firebaseapp.com',
    storageBucket: 'authfancy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjP6IPYWituSNcebfqkmeo88YjVYa1Hk',
    appId: '1:34126164944:android:866b8ef4e23b40f28abfd5',
    messagingSenderId: '34126164944',
    projectId: 'authfancy',
    storageBucket: 'authfancy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bMu2smaZN58KkgIFOQ8rBSUjgrnfLWw',
    appId: '1:34126164944:ios:8030b64c2978d42a8abfd5',
    messagingSenderId: '34126164944',
    projectId: 'authfancy',
    storageBucket: 'authfancy.appspot.com',
    iosBundleId: 'com.example.tugasbesar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bMu2smaZN58KkgIFOQ8rBSUjgrnfLWw',
    appId: '1:34126164944:ios:b47f107763f0711d8abfd5',
    messagingSenderId: '34126164944',
    projectId: 'authfancy',
    storageBucket: 'authfancy.appspot.com',
    iosBundleId: 'com.example.tugasbesar.RunnerTests',
  );
}
